name: google_wallet_button_example
description: Demonstrates the google_wallet_button package.
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_wallet_button:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
